package arr.cate.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import arr.cate.model.ShopDao;

import arr.cate.model.ShopDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopDaoDaoConfig;

    private final ShopDaoDao shopDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopDaoDaoConfig = daoConfigMap.get(ShopDaoDao.class).clone();
        shopDaoDaoConfig.initIdentityScope(type);

        shopDaoDao = new ShopDaoDao(shopDaoDaoConfig, this);

        registerDao(ShopDao.class, shopDaoDao);
    }
    
    public void clear() {
        shopDaoDaoConfig.getIdentityScope().clear();
    }

    public ShopDaoDao getShopDaoDao() {
        return shopDaoDao;
    }

}
